version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=mysql://root:root@mysql_db:3306/nest_database
    ports:
      - 3000:3000
    volumes:
      - .\.:/usr/src/api
  mysql_db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest_database
      - MYSQL_USER=nest_username
      - MYSQL_PASSWORD=nest_password
      - MYSQL_TCP_PORT=3306
