version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
      # - DATABASE_URL=postgres://nest_username:nest_password@db:5432/nest_dbname
    ports:
      - "3000:3000"
    volumes:
      - . :/usr/src/api
    # depends_on:
    #   - db
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - PORT=3001
      # - DATABASE_URL=postgres://nest_username:nest_password@db:5432/nest_dbname
    ports:
      - "3001:3001"
    volumes:
    - . :/usr/src/api
    # depends_on:
    #   - db
  # db:
  #   image: postgres:13
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=nest_username
  #     - POSTGRES_nest_PASSWORD=password
  #     - POSTGRES_DB=nest_dbname
