version: '3.8'
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:root@db:5432/nest_database
    ports:
      - 3001:3001
    volumes:
      - .\.:/usr/src/api
  mysql_db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest_database
      - MYSQL_USER=nest_username
      - MYSQL_PASSWORD=nest_password
      - MYSQL_TCP_PORT=3306
