version: '3.8'
services:
  api:
    build: .
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://nest_username:nest_password@db:5432/nest_dbname

    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=nest_username
      - POSTGRES_nest_PASSWORD=password
      - POSTGRES_DB=nest_dbname
