version: '3.8'
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - PORT=3001
      # - DATABASE_URL=postgres://nest_username:nest_password@db:5432/nest_dbname
    ports:
      - 3001:3001
    volumes:
      - .\src:/usr/src/api/src
  mysql_db:
    image: mysql
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=nest_database
      - MYSQL_USER=nest_username
      - MYSQL_PASSWORD=nest_password
      - MYSQL_TCP_PORT=3307
