version: '3.8'
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - PORT=3001
      # - DATABASE_URL=postgres://nest_username:nest_password@db:5432/nest_dbname
    ports:
      - 3001:3001
    volumes:
    - ./src:/usr/src/api/src
    # depends_on:
    #   - db
  # db:
  #   image: postgres:13
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=nest_username
  #     - POSTGRES_nest_PASSWORD=password
  #     - POSTGRES_DB=nest_dbname
