FROM node:alpine
WORKDIR /usr/src/api

COPY . .
COPY ./.env.production ./.env

RUN npm install --quiet --no-optional --no-fund --loglevel=error
RUN npm run build
RUN rm -rf ./src

EXPOSE 3001
CMD ["npm", "run", "start:prod"]
